### ISSUE TITLE
Unable to install via tpm on MacOS

### ISSUE THREAD

**Issue by LittleHendrix** [rose-pine/tmux#31]
Doesn't install via `tpm` on MacOS for some reason. 

OS: MacOS Sonoma Version 14.4
Tmux: 3.4
Terminal: Kitty

Running `prefix + I` doesn't now trigger install of `rose-pine/tmux` like with other plugins for some reason.

![image](https://github.com/rose-pine/tmux/assets/1037065/b3001aa5-3995-453f-a59d-09f8667c69cf)
![image](https://github.com/rose-pine/tmux/assets/1037065/719cba54-4601-45c5-8435-c2850deb671a)
![image](https://github.com/rose-pine/tmux/assets/1037065/867e6ef2-1628-4d5f-857d-b666ff070987)

**Comment by man-bug** [comment]
Same issue.

OS: MacOS Sonoma 14.3.1
Tmux: 3.4 
Terminal: Alacritty

```
# ~/.tmux.conf
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'moon'

set -g @rose_pine_host 'on' # Enables hostname in the status bar
set -g @rose_pine_date_time '' # It accepts the date UNIX command format (man date for info)
set -g @rose_pine_user 'on' # Turn on the username component in the statusbar
set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar
set -g @rose_pine_bar_bg_disable 'on' # Disables background color, for transparent terminal emulators
# If @rose_pine_bar_bg_disable is set to 'on', uses the provided value to set the background color
# It can be any of the on tmux (named colors, 256-color set, `default` or hex colors)
# See more on http://man.openbsd.org/OpenBSD-current/man1/tmux.1#STYLES
set -g @rose_pine_bar_bg_disabled_color_option 'default'

set -g @rose_pine_only_windows 'on' # Leaves only the window module, for max focus and space
set -g @rose_pine_disable_active_window_menu 'on' # Disables the menu that shows the active window on the left

set -g @rose_pine_default_window_behavior 'on' # Forces tmux default window list behaviour
set -g @rose_pine_show_current_program 'on' # Forces tmux to show the current running program as window name
set -g @rose_pine_show_pane_directory 'on' # Forces tmux to show the current directory as window name
# Previously set -g @rose_pine_window_tabs_enabled

# Example values for these can be:
set -g @rose_pine_left_separator ' > ' # The strings to use as separators are 1-space padded
set -g @rose_pine_right_separator ' < ' # Accepts both normal chars & nerdfont icons
set -g @rose_pine_field_separator ' | ' # Again, 1-space padding, it updates with prefix + I
set -g @rose_pine_window_separator ' - ' # Replaces the default `:` between the window number and name

# These are not padded
set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
set -g @rose_pine_current_window_icon '' # Changes the default icon to the left of the active window name
set -g @rose_pine_folder_icon '' # Changes the default icon to the left of the current directory folder
set -g @rose_pine_username_icon '' # Changes the default icon to the right of the hostname
set -g @rose_pine_hostname_icon '󰒋' # Changes the default icon to the right of the hostname
set -g @rose_pine_date_time_icon '󰃰' # Changes the default icon to the right of the date module
set -g @rose_pine_window_status_separator "  " # Changes the default icon that appears between window names

# Very beta and specific opt-in settings, tested on v3.2a, look at issue #10
set -g @rose_pine_prioritize_windows 'on' # Disables the right side functionality in a certain window count / terminal width
set -g @rose_pine_width_to_hide '80' # Specify a terminal width to toggle off most of the right side functionality
set -g @rose_pine_window_count '5' # Specify a number of windows, if there are more than the number, do the same as width_to_hide

run '~/.tmux/plugins/tpm/tpm'
```

![image](https://github.com/rose-pine/tmux/assets/136141397/f2348e33-a34b-401c-a687-6b7dc9a9440d)

Steps taken:
* Source tmux config
* TPM install, update
* Restarted tmux

**Comment by mrs4ndman** [comment]
Have you tried what the user on #28 did? Sometimes other plugins share the `repo-name/tmux` naming convention and that leaves 2 folders with the same name (`.tmux/plugins/tmux`). I'd suggest deleting the contents of `~/.tmux/plugins` (except for TPM) and trying to download it again.

**Comment by man-bug** [comment]
oops, sorry! should have checked the closed issues. it was a different plugin.

**Comment by mrs4ndman** [comment]
So, these seem like namespaces conflicting with other themes.
Did it get fixed for you guys or is it an issue?

**Comment by man-bug** [comment]
> So, these seem like namespaces conflicting with other themes. Did it get fixed for you guys or is it an issue?

Fixed! Your original comment helped me resolve the issue. if I remember correctly, I had previously installed another theme with the same namespace and removed it. No issues since [my second comment](https://github.com/rose-pine/tmux/issues/31#issuecomment-2108582682).

**Comment by mrs4ndman** [comment]
> > So, these seem like namespaces conflicting with other themes. Did it get fixed for you guys or is it an issue?
> 
> Fixed! Your original comment helped me resolve the issue. if I remember correctly, I had previously installed another theme with the same namespace and removed it. No issues since [my second comment](https://github.com/rose-pine/tmux/issues/31#issuecomment-2108582682).

Great! Happy to see it works for you :)

@LittleHendrix Is it still a persisting issue?

**Comment by stefumies** [comment]
I still have the same issue and noticed that the theme isn't installed into the` plugins `directory directly but into the '`plugins/tmux` folder on mac, as such the theme is not read in tmux. I assume as the plugin call is `rose-pine/tmux` rather than `tmux-plugins/rose-pine`

**Comment by stefumies** [comment]
This is still unfixed, is there no movement on this?

**Comment by mrs4ndman** [comment]
The thing is: 
- The route for the plugin to install (at least in Linux / *nix machines) is the standard for all TPM-installed plugins: `$HOME/.tmux/plugins/<name of plugin>`. I can't change how TPM installs the plugin itself.
- Because of naming conventions in the `rose-pine` org, the theme plugin names have to be `rose-pine/<name of program>`, so the route that TPM has for this plugin WILL CAUSE CONFLICT if another plugin with the same naming scheme is installed. Once again, I do not know how to correct this behaviour.

The namespace conflicts with tmux plugins are known :smiling_face_with_tear:

**Comment by oatovar** [comment]
> The namespace conflicts with tmux plugins are known 🥲

Is there a FAQ or troubleshooting doc that we can add this to? I searched the tpm and theme repos for something that would resolve this, but only found it after searching the issues.

**Comment by mrs4ndman** [comment]
> > The namespace conflicts with tmux plugins are known 🥲
> 
> Is there a FAQ or troubleshooting doc that we can add this to? I searched the tpm and theme repos for something that would resolve this, but only found it after searching the issues.

@oatovar Started the wiki and added this as a first entry for it

**Comment by mrs4ndman** [comment]
Since it came down to a name colission, this doesn't need to be open anymore. If anyone is still having issues related to this, either comment on here or open another issue. Thanks for the help! :sweat_smile:
